/*
   mini-LZ library (mlz)
   (c) Martin Sedlak 2016-2018

   Boost Software License - Version 1.0 - August 17th, 2003

   Permission is hereby granted, free of charge, to any person or organization
   obtaining a copy of the software and accompanying documentation covered by
   this license (the "Software") to use, reproduce, display, distribute,
   execute, and transmit the Software, and to prepare derivative works of the
   Software, and to permit third-parties to whom the Software is furnished to
   do so, all subject to the following:

   The copyright notices in the Software and this entire statement, including
   the above license grant, this restriction and the following disclaimer,
   must be included in all copies of the Software, in whole or in part, and
   all derivative works of the Software, unless such copies or derivative
   works are solely in the form of machine-executable object code generated by
   a source language processor.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
   SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
   FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE.
*/

#include "mlz_stream_dec.h"
#include "mlz_dec.h"
/* mlz_malloc, mlz_free */
#include "mlz_enc.h"
#include <stdio.h>
#include <string.h>

static mlz_intptr mlz_stream_read_wrapper(void *handle, void *buf, mlz_intptr size)
{
	size_t res = (size_t)fread(buf, 1, size, (FILE *)handle);
	return ferror((FILE *)handle) ? -1 : (mlz_intptr)res;
}

static mlz_intptr mlz_stream_write_wrapper(void *handle, MLZ_CONST void *buf, mlz_intptr size)
{
	size_t res = (size_t)fwrite(buf, 1, size, (FILE *)handle);
	return ferror((FILE *)handle) ? -1 : (mlz_intptr)res;
}

static mlz_bool mlz_stream_rewind_wrapper(void *handle)
{
	return fseek((FILE *)handle, 0, SEEK_SET) == 0;
}

static mlz_bool mlz_stream_close_wrapper(void *handle)
{
	return fclose((FILE *)handle) == 0;
}

/* simple adler32 checksum (Mark Adler's Fletcher variant) */
mlz_uint
mlz_adler32(
	MLZ_CONST void *buf,
	size_t size,
	mlz_uint checksum
)
{
	MLZ_CONST mlz_byte *b = (MLZ_CONST mlz_byte *)buf;
	mlz_uint hi = (checksum >> 16);
	mlz_uint lo = checksum & 0xffffu;

	MLZ_ASSERT(buf);

	while (size >= 5552) {
		/* fast path */
		mlz_uint i;
		for (i=5552/16; i>0; i--) {
			lo += *b++;
			hi += lo;
			lo += *b++;
			hi += lo;
			lo += *b++;
			hi += lo;
			lo += *b++;
			hi += lo;
			lo += *b++;
			hi += lo;
			lo += *b++;
			hi += lo;
			lo += *b++;
			hi += lo;
			lo += *b++;
			hi += lo;
			lo += *b++;
			hi += lo;
			lo += *b++;
			hi += lo;
			lo += *b++;
			hi += lo;
			lo += *b++;
			hi += lo;
			lo += *b++;
			hi += lo;
			lo += *b++;
			hi += lo;
			lo += *b++;
			hi += lo;
			lo += *b++;
			hi += lo;
		}
		lo %= 65521;
		hi %= 65521;
		size -= 5552;
	}

	while (size >= 4) {
		lo += *b++;
		hi += lo;
		lo += *b++;
		hi += lo;
		lo += *b++;
		hi += lo;
		lo += *b++;
		hi += lo;
		size -= 4;
	}

	while (size--) {
		lo += *b++;
		hi += lo;
	}

	lo %= 65521;
	hi %= 65521;

	return lo | (hi << 16);
}

mlz_uint
mlz_adler32_simple(
	MLZ_CONST void *buf,
	size_t size
)
{
	return mlz_adler32(buf, size, 1);
}

MLZ_CONST mlz_stream_params mlz_default_stream_params = {
	/* user data (handle) */
	MLZ_NULL,
	/* multi-threaded */
	MLZ_NULL,
	mlz_stream_read_wrapper,
	mlz_stream_write_wrapper,
	mlz_stream_rewind_wrapper,
	mlz_stream_close_wrapper,
	MLZ_NULL,
	/* compressed block checksum function, returns 32-bit hash */
	MLZ_NULL,
	/* incremental uncompressed checksum function */
	mlz_adler32,
	/* initial value for incremental checksum   */
	1,
	/* desired block size, 65536 is recommended */
	65536,
	/* independent blocks flag */
	MLZ_FALSE,
	/* unsafe flag */
	MLZ_FALSE,
	/* stream header flag */
	MLZ_TRUE
};

mlz_in_stream *
mlz_in_stream_open(
	MLZ_CONST mlz_stream_params *params
)
{
	mlz_byte       *buf;
	mlz_in_stream  *ins;
	mlz_int         context_size, reserve, num_threads;
	mlz_int         block_size;
	mlz_bool        use_header;
	mlz_byte        hdr[2];

	hdr[0] = hdr[1] = 0;

	/* params and read function test */
	MLZ_RET_FALSE(params && params->read_func);

	block_size = params->block_size;
	use_header = params->use_header;

	if (use_header) {
		/* simple 2-byte block header                */
		/* bits 4-0: log2(block_size)                */
		/* bit 5   : independent                     */
		/* bit 6   : use block checksum (adler32)    */
		/* bit 7   : use incremental chsum (adler32) */
		/* 2nd byte = ~hdr (validation)              */
		MLZ_RET_FALSE(params->read_func(params->handle, hdr, 2) == 2);
		MLZ_RET_FALSE(hdr[0] == (mlz_byte)~hdr[1]);
		block_size = (mlz_int)1 << (hdr[0] & 31);
	}

	/* block size test */
	MLZ_RET_FALSE(block_size >= MLZ_MIN_BLOCK_SIZE && block_size < MLZ_MAX_BLOCK_SIZE);
	/* power of two test */
	MLZ_RET_FALSE(!((mlz_uint)block_size & ((mlz_uint)block_size-1)));

	ins = (mlz_in_stream *)mlz_malloc(sizeof(mlz_in_stream));
	MLZ_RET_FALSE(ins);

#if defined(MLZ_THREADS)
	ins->mutex = mlz_mutex_create();
	if (!ins->mutex) {
		mlz_free(ins);
		return MLZ_NULL;
	}
#endif

	ins->params = *params;
	if (use_header) {
		ins->params.block_size           = block_size;
		ins->params.independent_blocks   = (hdr[0] & 0x20) != 0;
		ins->params.block_checksum       = MLZ_NULL;
		ins->params.incremental_checksum = MLZ_NULL;
		if ((hdr[0] & 0x40) != 0)
			ins->params.block_checksum = mlz_adler32_simple;
		if ((hdr[0] & 0x80) != 0)
			ins->params.incremental_checksum = mlz_adler32;
		/* adler32 init */
		ins->params.initial_checksum = 1;
	}

	context_size = MLZ_BLOCK_CONTEXT_SIZE;
	if (context_size > block_size)
		context_size = block_size;

	num_threads = 1;

	if (ins->params.independent_blocks) {
		context_size = 0;
#if defined(MLZ_THREADS)
		if (params->jobs) {
			num_threads += params->jobs->num_threads;
			if (num_threads < 1 || num_threads > MLZ_MAX_THREADS) {
				(void)mlz_mutex_destroy(ins->mutex);
				mlz_free(ins);
				return MLZ_NULL;
			}
		}
#endif
	}

	/* in-place decompress reserve (max inflation is 1 bit per byte) */
	reserve = block_size/8 + MLZ_CACHELINE_ALIGN;

	ins->buffer_unaligned = buf = (mlz_byte *)mlz_malloc(context_size + (block_size + reserve)*num_threads + MLZ_CACHELINE_ALIGN-1);
	if (!buf) {
#if defined(MLZ_THREADS)
		(void)mlz_mutex_destroy(ins->mutex);
#endif
		mlz_free(ins);
		return MLZ_NULL;
	}

	buf = (mlz_byte *)((mlz_uintptr)buf & ~((mlz_uintptr)MLZ_CACHELINE_ALIGN-1));
	if (buf < ins->buffer_unaligned)
		buf += MLZ_CACHELINE_ALIGN;

	MLZ_ASSERT(buf >= ins->buffer_unaligned);
	ins->buffer = buf;

	ins->checksum        = ins->params.initial_checksum;
	ins->block_size      = block_size;
	ins->block_reserve   = reserve;
	ins->context_size    = context_size;
	ins->next_block_size = 0;
	ins->num_threads     = num_threads;
	ins->current_block   = 0;
	ins->num_blocks      = 0;
	ins->ptr             = MLZ_NULL;
	ins->top             = MLZ_NULL;
	ins->is_eof          = MLZ_FALSE;
	ins->first_block     = MLZ_TRUE;
	ins->first_cached    = MLZ_FALSE;
	return ins;
}

static mlz_bool mlz_read_little_endian(mlz_in_stream *stream, mlz_uint *val)
{
	mlz_byte buf[4];
	MLZ_ASSERT(val);
	MLZ_RET_FALSE(stream->params.read_func(stream->params.handle, buf, 4) == 4);
	*val = buf[0] + (buf[1] << 8) + (buf[2] << 16) + ((mlz_uint)buf[3] << 24);
	return MLZ_TRUE;
}

static void mlz_decompress_block_job(int thread, void *param)
{
	mlz_in_stream *stream = (mlz_in_stream *)param;

	mlz_int blk_ofs  = thread * (stream->block_size + stream->block_reserve);
	mlz_byte *target = stream->block_targets[thread];
	mlz_int blk_size = stream->blk_sizes[thread];

	if (!stream->unc_blocks[thread]) {
		mlz_int usize = stream->usizes[thread];
		/* and finally: decompress (in-place) */
		size_t dlen = stream->params.unsafe ?
			mlz_decompress_unsafe(stream->buffer + stream->context_size + blk_ofs, target,
			blk_size)
			: mlz_decompress(stream->buffer + stream->context_size + blk_ofs, usize, target,
				blk_size, stream->context_size * (stream->first_block != MLZ_TRUE));
#if defined(MLZ_THREADS)
		(void)mlz_mutex_lock(stream->mutex);
		stream->dlens[thread] = dlen;
		(void)mlz_mutex_unlock(stream->mutex);
#else
		stream->dlens[thread] = dlen;
#endif
	}
}

static mlz_bool
mlz_in_stream_read_block(mlz_in_stream *stream)
{
	mlz_uint  blk_size;
	mlz_uint  usize;
	mlz_int   i;
	mlz_byte *target;
	mlz_uint  block_checksum = 0;
	mlz_int   in_blocks = 0;
	mlz_int   in_blocks_threaded = 0;

	stream->current_block = 0;
	stream->num_blocks    = 0;

	blk_size = 0;
	for (i=0; i<stream->num_threads; i++) {
		mlz_bool  partial, uncompressed;
		mlz_int   target_pos;
		mlz_int   blk_ofs = i*(stream->block_size + stream->block_reserve);

		if (stream->next_block_size) {
			blk_size = stream->next_block_size;
			stream->next_block_size = 0;
		} else {
			MLZ_RET_FALSE(mlz_read_little_endian(stream, &blk_size));
		}

		partial      = (blk_size & MLZ_PARTIAL_BLOCK_MASK) != 0;
		uncompressed = (blk_size & MLZ_UNCOMPRESSED_BLOCK_MASK) != 0;

		blk_size &= MLZ_BLOCK_LEN_MASK;

		MLZ_RET_FALSE(blk_size <= (mlz_uint)stream->block_size);

		if (blk_size == 0)
			break;

		usize = stream->block_size;

		/* load block checksum if needed */
		if (stream->params.block_checksum)
			MLZ_RET_FALSE(mlz_read_little_endian(stream, &block_checksum));

		if (partial)
			MLZ_RET_FALSE(mlz_read_little_endian(stream, &usize) &&
				usize > 0 && usize <= (mlz_uint)stream->block_size);

		target_pos = stream->context_size + blk_ofs + (stream->block_size + stream->block_reserve) - blk_size;
		/* make sure buffer is aligned, we have reserve anyway */
		target_pos &= ~(mlz_uintptr)7;

		target = stream->buffer + target_pos;
		if (uncompressed)
			/* special handling of uncompressed blocks */
			target = stream->buffer + stream->context_size + blk_ofs;

		stream->blk_sizes[in_blocks]       = blk_size;
		stream->usizes[in_blocks]          = usize;
		stream->unc_blocks[in_blocks]      = uncompressed;
		stream->block_targets[in_blocks++] = target;

		in_blocks_threaded += (i>0) && !uncompressed;

		MLZ_RET_FALSE(stream->params.read_func(stream->params.handle, target,
			(mlz_intptr)blk_size) == (mlz_intptr)blk_size);

		/* validate compressed checksum */
		if (!stream->params.unsafe && stream->params.block_checksum)
			MLZ_RET_FALSE(stream->params.block_checksum(target, blk_size) == block_checksum);
	}

	(void)in_blocks_threaded;
#if defined(MLZ_THREADS)
	MLZ_RET_FALSE(!stream->params.jobs || mlz_jobs_prepare_batch(stream->params.jobs, in_blocks_threaded));
	for (i=1; i<in_blocks; i++) {
		mlz_job job;
		if (stream->unc_blocks[i])
			continue;
		job.param = stream;
		job.job = mlz_decompress_block_job;
		job.idx = i;
		MLZ_RET_FALSE(mlz_jobs_enqueue(stream->params.jobs, job));
	}
#endif
	/* this thread helps too */
	mlz_decompress_block_job(0, stream);
#if defined(MLZ_THREADS)
	MLZ_RET_FALSE(in_blocks < 2 || mlz_jobs_wait(stream->params.jobs));
#endif

	stream->ptr = stream->buffer + stream->context_size;

	for (i=0; i<in_blocks; i++) {
		mlz_int ofs = (stream->block_size + stream->block_reserve)*i;
		usize = stream->usizes[i];

		/* handle decompression errors now */
		if (!stream->unc_blocks[i] && stream->dlens[i] != (size_t)usize)
			return MLZ_FALSE;

		/* compute incremental checksum if needed */
		if (stream->params.incremental_checksum)
			stream->checksum =
				stream->params.incremental_checksum(stream->buffer + stream->context_size + ofs,
					usize, stream->checksum);
	}

	usize = stream->usizes[0];
	stream->top = stream->ptr + usize;

	/* copy context */
	if (stream->context_size > 0 && usize >= (size_t)stream->context_size)
		memcpy(stream->buffer, stream->buffer + usize, stream->context_size);

	stream->first_cached = stream->first_block;
	stream->first_block  = MLZ_FALSE;

	stream->num_blocks   = in_blocks;

	if (blk_size) {
		/* precache next block size to see if it's last block, this is important for checksum verification */
		mlz_uint next_blk_size;
		MLZ_RET_FALSE(mlz_read_little_endian(stream, &next_blk_size));
		stream->next_block_size = next_blk_size;
		if (!next_blk_size)
			blk_size = 0;
	}

	if (blk_size == 0) {
		if (!stream->params.unsafe && stream->params.incremental_checksum) {
			mlz_uint checksum;
			MLZ_RET_FALSE(mlz_read_little_endian(stream, &checksum) &&
				checksum == stream->checksum);
		}
		stream->is_eof = MLZ_TRUE;
		if (in_blocks == 0)
			stream->ptr = stream->top = MLZ_NULL;
	}

	return MLZ_TRUE;
}

mlz_intptr
mlz_stream_read(
	mlz_in_stream *stream,
	void          *buf,
	mlz_intptr     size
)
{
	mlz_intptr nread = 0;
	mlz_byte *db = (mlz_byte *)buf;

	MLZ_ASSERT(stream);

	while (size > 0) {
		mlz_intptr to_fill, capacity;

		if (stream->ptr >= stream->top) {
			if (++stream->current_block < stream->num_blocks) {
				/* jump to next block */
				stream->ptr = stream->buffer + stream->context_size +
					stream->current_block * (stream->block_size + stream->block_reserve);
				stream->top = stream->ptr + stream->usizes[stream->current_block];
				continue;
			}
			if (stream->is_eof)
				break;

			/* read next block */
			if (!mlz_in_stream_read_block(stream))
				return -1;
		}

		to_fill = size;
		capacity = (mlz_intptr)(stream->top - stream->ptr);
		if (to_fill > capacity)
			to_fill = capacity;

		if (to_fill > 0) {
			if (db) {
				memcpy(db, stream->ptr, to_fill);
				db += to_fill;
			}
			stream->ptr += to_fill;
			size        -= to_fill;
			nread       += to_fill;
		}
	}

	return nread;
}

mlz_bool
mlz_in_stream_rewind(
	mlz_in_stream *stream
)
{
	mlz_byte hdr[2];

	MLZ_RET_FALSE(stream);

	if (stream->first_cached) {
		/* fast rewind */
		stream->ptr           = stream->buffer + stream->context_size;
		stream->current_block = 0;
		return MLZ_TRUE;
	}

	MLZ_RET_FALSE(stream->params.rewind_func && stream->params.rewind_func(stream->params.handle));

	stream->ptr             = MLZ_NULL;
	stream->top             = MLZ_NULL;
	stream->checksum        = stream->params.initial_checksum;
	stream->is_eof          = MLZ_FALSE;
	stream->first_block     = MLZ_TRUE;
	stream->first_cached    = MLZ_FALSE;
	stream->next_block_size = 0;

	/* skip header if necessary */
	return stream->params.use_header ?
		stream->params.read_func(stream->params.handle, hdr, 2) == 2 : MLZ_TRUE;
}

mlz_bool
mlz_in_stream_close(
	mlz_in_stream *stream
)
{
	MLZ_RET_FALSE(stream);

	if (stream->params.close_func)
		MLZ_RET_FALSE(stream->params.close_func(stream->params.handle));

#if defined(MLZ_THREADS)
	MLZ_RET_FALSE(mlz_mutex_destroy(stream->mutex));
#endif

	mlz_free(stream->buffer_unaligned);
	mlz_free(stream);
	return MLZ_TRUE;
}

mlz_bool
mlz_in_stream_eof(
	mlz_in_stream *stream
)
{
	return stream && stream->is_eof;
}
